# Generated by Django 5.1.7 on 2025-04-05 05:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="场景名称")),
                ("category", models.CharField(max_length=50, verbose_name="场景分类")),
                ("description", models.TextField(verbose_name="场景描述")),
                (
                    "target_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        size=None,
                        verbose_name="目标角色",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("version", models.CharField(max_length=20, verbose_name="版本号")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景",
                "verbose_name_plural": "场景",
                "db_table": "scenes",
            },
        ),
        migrations.CreateModel(
            name="SceneTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                ("description", models.TextField(verbose_name="任务描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="scenes.scene",
                        verbose_name="所属场景",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates.template",
                        verbose_name="关联模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景任务",
                "verbose_name_plural": "场景任务",
                "db_table": "scene_tasks",
            },
        ),
        migrations.CreateModel(
            name="SceneTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                (
                    "parameters",
                    models.JSONField(blank=True, null=True, verbose_name="参数配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="scenes.scene",
                        verbose_name="所属场景",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates.template",
                        verbose_name="关联模版",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景模版关联",
                "verbose_name_plural": "场景模版关联",
                "db_table": "scene_templates",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="SceneUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="使用时间"),
                ),
                (
                    "feedback_score",
                    models.IntegerField(blank=True, null=True, verbose_name="反馈评分"),
                ),
                (
                    "feedback_content",
                    models.TextField(blank=True, null=True, verbose_name="反馈内容"),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="scenes.scene",
                        verbose_name="所属场景",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="templates.template",
                        verbose_name="使用模版",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景使用统计",
                "verbose_name_plural": "场景使用统计",
                "db_table": "scene_usage",
            },
        ),
        migrations.CreateModel(
            name="SceneVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(max_length=20, verbose_name="版本号"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="版本描述"),
                ),
                ("content", models.JSONField(verbose_name="版本内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="scenes.scene",
                        verbose_name="所属场景",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景版本",
                "verbose_name_plural": "场景版本",
                "db_table": "scene_versions",
            },
        ),
        migrations.AddIndex(
            model_name="scene",
            index=models.Index(
                fields=["name", "category", "status"], name="scenes_name_4cfbd6_idx"
            ),
        ),
    ]
