# Generated by Django 5.1.7 on 2025-03-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenes", "0001_initial"),
        ("templates", "0007_alter_templatetest_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenetask",
            name="output_requirements",
        ),
        migrations.RemoveField(
            model_name="scenetask",
            name="task_type",
        ),
        migrations.AddField(
            model_name="scenetask",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="templates.template",
                verbose_name="关联模板",
            ),
        ),
    ]
