# Generated by Django 5.1.7 on 2025-03-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scenes", "0002_update_scene_task_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenetask",
            name="applicable_roles",
        ),
    ]
