# Generated by Django 5.1.7 on 2025-03-22 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "私有"),
                            ("PUBLIC", "公开"),
                            ("SHARED", "共享"),
                        ],
                        default="PRIVATE",
                        max_length=10,
                        verbose_name="可见性",
                    ),
                ),
                (
                    "framework_type",
                    models.CharField(
                        choices=[
                            ("RTGO", "RTGO"),
                            ("SPAR", "SPAR"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=10,
                        verbose_name="框架类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="描述")),
                ("content", models.JSONField(verbose_name="内容")),
                ("variables", models.JSONField(default=list, verbose_name="变量")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "target_role",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="适用角色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "提示词模板",
                "verbose_name_plural": "提示词模板",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("GPT-3.5", "GPT-3.5"),
                            ("GPT-4", "GPT-4"),
                            ("CLAUDE", "Claude"),
                        ],
                        max_length=20,
                        verbose_name="测试模型",
                    ),
                ),
                ("input_data", models.JSONField(verbose_name="输入数据")),
                ("output_content", models.TextField(verbose_name="输出内容")),
                (
                    "prompt",
                    models.TextField(
                        blank=True, null=True, verbose_name="生成的提示词"
                    ),
                ),
                (
                    "dify_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dify API响应"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="templates.template",
                        verbose_name="测试模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板测试",
                "verbose_name_plural": "模板测试",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_edit", models.BooleanField(default=False, verbose_name="可编辑")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("ACCEPTED", "已接受"),
                            ("REJECTED", "已拒绝"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_with_me",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被分享用户",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="templates.template",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "共享模板",
                "verbose_name_plural": "共享模板",
                "unique_together": {("template", "shared_with")},
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(verbose_name="版本号")),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "framework_type",
                    models.CharField(
                        choices=[
                            ("RTGO", "RTGO"),
                            ("SPAR", "SPAR"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=10,
                        verbose_name="框架类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="描述")),
                ("content", models.JSONField(verbose_name="内容")),
                ("variables", models.JSONField(default=list, verbose_name="变量")),
                (
                    "target_role",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="适用角色"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="是否为当前版本"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="templates.template",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "提示词模板版本",
                "verbose_name_plural": "提示词模板版本",
                "ordering": ["-version_number"],
                "unique_together": {("template", "version_number")},
            },
        ),
    ]
