# Generated by Django 5.1.6 on 2025-03-20 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "framework_type",
                    models.CharField(
                        choices=[
                            ("RTGO", "RTGO"),
                            ("SPAR", "SPAR"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=10,
                        verbose_name="框架类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="描述")),
                ("content", models.JSONField(verbose_name="内容")),
                ("variables", models.JSONField(default=list, verbose_name="变量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "提示词模板",
                "verbose_name_plural": "提示词模板",
                "ordering": ["-created_at"],
            },
        ),
    ]
