# Generated by Django 5.1.7 on 2025-03-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frameworks", "0001_initial"),
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="framework_type",
        ),
        migrations.RemoveField(
            model_name="templateversion",
            name="framework_type",
        ),
        migrations.AddField(
            model_name="template",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="frameworks.framework",
                verbose_name="框架",
            ),
        ),
        migrations.AddField(
            model_name="templateversion",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="frameworks.framework",
                verbose_name="框架",
            ),
        ),
    ]
