# Generated by Django 5.1.6 on 2025-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="target_role",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="适用角色"
            ),
        ),
        migrations.AddField(
            model_name="templateversion",
            name="target_role",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="适用角色"
            ),
        ),
    ]
