# Generated by Django 5.1.7 on 2025-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0002_remove_template_framework_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="framework_type",
            field=models.CharField(
                choices=[("RTGO", "RTGO"), ("SPAR", "SPAR"), ("CUSTOM", "自定义")],
                default="CUSTOM",
                max_length=20,
                verbose_name="框架类型",
            ),
        ),
    ]
