# Generated by Django 5.1.6 on 2025-03-20 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0002_templateversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="template",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "提示词模板",
                "verbose_name_plural": "提示词模板",
            },
        ),
        migrations.AddField(
            model_name="template",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
        migrations.CreateModel(
            name="TemplateTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("GPT-3.5", "GPT-3.5"),
                            ("GPT-4", "GPT-4"),
                            ("CLAUDE", "Claude"),
                        ],
                        max_length=20,
                        verbose_name="测试模型",
                    ),
                ),
                ("input_data", models.JSONField(verbose_name="输入数据")),
                ("output_content", models.TextField(verbose_name="输出内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="templates.template",
                        verbose_name="测试模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "模板测试",
                "verbose_name_plural": "模板测试",
                "ordering": ["-created_at"],
            },
        ),
    ]
