# Generated by Django 5.1.7 on 2025-03-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0003_add_shared_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="visibility",
            field=models.CharField(
                choices=[("PRIVATE", "私有"), ("PUBLIC", "公开"), ("SHARED", "共享")],
                default="PRIVATE",
                max_length=10,
                verbose_name="可见性",
            ),
        ),
    ]
