# Generated by Django 5.1.7 on 2025-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0003_template_framework_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="framework_type",
            field=models.CharField(
                choices=[], default="CUSTOM", max_length=100, verbose_name="框架类型"
            ),
        ),
    ]
