# Generated by Django 5.1.7 on 2025-03-24 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frameworks", "0001_initial"),
        ("templates", "0004_update_framework_type_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateversion",
            name="framework_type",
            field=models.CharField(
                choices=[], default="CUSTOM", max_length=100, verbose_name="框架类型"
            ),
        ),
        migrations.AlterField(
            model_name="templateversion",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="template_versions",
                to="frameworks.framework",
                verbose_name="框架",
            ),
        ),
        migrations.AlterField(
            model_name="templateversion",
            name="version_number",
            field=models.IntegerField(verbose_name="版本号"),
        ),
    ]
