# Generated by Django 5.1.7 on 2025-03-25 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frameworks", "0002_framework_created_by"),
        ("templates", "0005_templateversion_framework_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="frameworks.framework",
                verbose_name="框架",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="framework_type",
            field=models.CharField(choices=[], max_length=100, verbose_name="框架类型"),
        ),
        migrations.AlterField(
            model_name="templateversion",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_versions",
                to="frameworks.framework",
                verbose_name="框架",
            ),
        ),
    ]
