# Generated by Django 5.1.7 on 2025-03-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0005_update_existing_templates_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedtemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待确认"),
                    ("ACCEPTED", "已接受"),
                    ("REJECTED", "已拒绝"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="状态",
            ),
        ),
    ]
