# Generated by Django 5.1.7 on 2025-03-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0006_alter_template_framework_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetest",
            name="model",
            field=models.CharField(
                choices=[
                    ("GPT-3.5", "GPT-3.5"),
                    ("GPT-4", "GPT-4"),
                    ("CLAUDE", "Claude"),
                    ("Dify API", "Dify API"),
                ],
                max_length=20,
                verbose_name="测试模型",
            ),
        ),
    ]
