# Generated by Django 5.1.7 on 2025-03-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0006_sharedtemplate_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedtemplate",
            name="status",
        ),
    ]
