# Generated by Django 5.1.7 on 2025-03-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0007_remove_sharedtemplate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedtemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待处理"),
                    ("ACCEPTED", "已接受"),
                    ("REJECTED", "已拒绝"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="sharedtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
