# Generated by Django 5.1.7 on 2025-03-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0008_sharedtemplate_status_sharedtemplate_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetest",
            name="dify_response",
            field=models.JSONField(blank=True, null=True, verbose_name="Dify API响应"),
        ),
        migrations.AddField(
            model_name="templatetest",
            name="prompt",
            field=models.TextField(blank=True, null=True, verbose_name="生成的提示词"),
        ),
    ]
