# Generated by Django 5.1.7 on 2025-03-29 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frameworks", "0002_framework_created_by"),
        ("templates", "0008_revert_framework_type_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="frameworks.framework",
                verbose_name="框架",
            ),
        ),
        migrations.AddField(
            model_name="templateversion",
            name="framework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template_versions",
                to="frameworks.framework",
                verbose_name="框架",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="framework_type",
            field=models.CharField(choices=[], max_length=100, verbose_name="框架类型"),
        ),
        migrations.AlterField(
            model_name="templateversion",
            name="framework_type",
            field=models.CharField(
                choices=[], default="CUSTOM", max_length=100, verbose_name="框架类型"
            ),
        ),
    ]
