# Generated by Django 5.1.7 on 2025-04-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0010_convert_target_role_to_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="target_role",
            field=models.JSONField(blank=True, null=True, verbose_name="适用角色"),
        ),
        migrations.AlterField(
            model_name="templateversion",
            name="target_role",
            field=models.JSONField(blank=True, null=True, verbose_name="适用角色"),
        ),
    ]
