# Generated by Django 5.1.7 on 2025-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0012_alter_template_target_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="target_role",
            field=models.TextField(blank=True, null=True, verbose_name="适用角色"),
        ),
        migrations.AlterField(
            model_name="templateversion",
            name="target_role",
            field=models.TextField(blank=True, null=True, verbose_name="适用角色"),
        ),
    ]
