# Generated by Django 5.1.7 on 2025-03-23 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(max_length=100, verbose_name="平台名称"),
                ),
                (
                    "scene_name",
                    models.CharField(max_length=100, verbose_name="场景名称"),
                ),
                ("key", models.CharField(max_length=255, verbose_name="API秘钥")),
                ("description", models.TextField(blank=True, verbose_name="描述信息")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "API秘钥",
                "verbose_name_plural": "API秘钥",
                "ordering": ["-created_at"],
                "unique_together": {("platform_name", "scene_name", "user")},
            },
        ),
    ]
