# Generated by Django 5.1.7 on 2025-03-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Framework Name"
                    ),
                ),
                ("description", models.TextField(verbose_name="Framework Description")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Framework",
                "verbose_name_plural": "Frameworks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FrameworkModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Module Name")),
                ("description", models.TextField(verbose_name="Module Description")),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="frameworks.framework",
                        verbose_name="Framework",
                    ),
                ),
            ],
            options={
                "verbose_name": "Framework Module",
                "verbose_name_plural": "Framework Modules",
                "ordering": ["framework", "order", "created_at"],
                "unique_together": {("framework", "name")},
            },
        ),
    ]
